### ISSUE TITLE
Getting error on startup of hapi server

### ISSUE THREAD

**Issue by rmothilal** [krakenjs/hapi-openapi#177]
Hi, 

Im getting the following error when using the updated hapi-openapi library 2.0.1

`Error: Method no longer accepts array arguments: extend
    at new module.exports (/xxx/xxx/xxx/node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports (/xxx/xxx/xxx/node_modules/@hapi/hoek/lib/assert.js:20:11)
    at Object.exports.verifyFlat (/xxx/xxx/xxx/node_modules/@hapi/joi/lib/common.js:211:9)
    at Object.extend (/xxx/xxx/xxx/node_modules/@hapi/joi/lib/index.js:151:16)
    at new SchemaResolver (/xxx/xxx/xxx/node_modules/enjoi/lib/resolver.js:36:24)
    at Object.schema (/xxx/xxx/xxx/node_modules/enjoi/index.js:43:20)
    at makeValidator (/xxx/xxx/xxx/node_modules/hapi-openapi/lib/validators.js:77:28)
    at Object.makeAll (/xxx/xxx/xxx/node_modules/hapi-openapi/lib/validators.js:155:31)
    at Object.create (/xxx/xxx/xxx/node_modules/hapi-openapi/lib/routes.js:77:37)
    at async Object.register (/xxx/xxx/xxx/node_modules/hapi-openapi/lib/index.js:168:20)
    at async internals.Server.register (/xxx/xxx/xxx/node_modules/@hapi/hapi/lib/server.js:466:17)
    at async createServer (/xxx/xxx/xxx/src/shared/setup.js:101:5)
    at async Object.initialize (/xxx/xxx/xxx/src/shared/setup.js:184:16)`

i am using @hapi/hapi: 19.1.1

**Comment by tlivings** [comment]
Is this happening in latest?

**Comment by rmothilal** [comment]
@tlivings will test and confirm

**Comment by rmothilal** [comment]
thanks again for the latest release

**Comment by rmothilal** [comment]
Seems to be resolved now @tlivings thanks
